name: odoo_apexive
description: "Completed a task for Volo to showcase my skills and deep knowledge in computer science, clean architecture, and strong proficiency in Flutter."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

